/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[nltk_data] Downloading package punkt to /home/borito1907/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/borito1907/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/runpy.py:126: RuntimeWarning: 'mutators.word' found in sys.modules after import of package 'mutators', but prior to execution of 'mutators.word'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data2/borito1907/impossibility-watermark/mutators/word.py", line 297, in <module>
    test()
  File "/data2/borito1907/impossibility-watermark/mutators/word.py", line 271, in test
    df = pd.read_csv('/data2/borito1907/impossibility-watermark/human_study/data/WQE/dev.csv')
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/local1/borito1907/anaconda3/envs/gptq/lib/python3.10/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data2/borito1907/impossibility-watermark/human_study/data/WQE/dev.csv'
