2024-05-24 01:05:10,308:INFO:Running command: python attack.py ++attack_args.prompt_file='./inputs/mini_c4.csv' ++attack_args.prompt_num=1 ++attack_args.watermarked_text_path='./inputs/c4_1.csv' ++attack_args.watermarked_text_num=1 ++attack_args.results_dir='./semstamp_attacks/c4/' ++watermark_args.save_file_name='c4_1.csv' ++watermark_args.only_detect=True ++attack_args.is_completion=True 
2024-05-24 01:05:10,309:INFO:Saving results to ./logs/semstamp_attacks/minic4_1_first.log
Traceback (most recent call last):
  File "/local1/borito1907/impossibility-watermark/run_attacks.py", line 50, in <module>
    main()
  File "/local1/borito1907/impossibility-watermark/run_attacks.py", line 40, in main
    stdout, stderr = run_command(command, log_filepath)
  File "/local1/borito1907/impossibility-watermark/run_attacks.py", line 15, in run_command
    result = subprocess.run(command, shell=True, check=True, text=True, stdout=f, stderr=subprocess.STDOUT)
  File "/local1/borito1907/anaconda3/envs/watermark_2/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/local1/borito1907/anaconda3/envs/watermark_2/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/local1/borito1907/anaconda3/envs/watermark_2/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/local1/borito1907/anaconda3/envs/watermark_2/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/local1/borito1907/anaconda3/envs/watermark_2/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
